services:
  postgres:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: 1
      POSTGRES_DB: 1
      POSTGRES_PASSWORD: 1
    networks:
      - bridge
    volumes:
      - pg_data:/var/lib/postgresql/data_4


  twitter_replica:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  pg_data:
    driver: local
