services:
  database:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    networks:
      - bridge
    volumes:
      - pg_data:/var/lib/postgresql/data


  facebook_replica:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  pg_data:
    driver: local
